# Generated by Django 4.2.1 on 2023-06-01 23:34

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('message', models.TextField()),
                ('subject', models.CharField(default=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='TRACKER ID')),
                ('sender_name', models.CharField(max_length=50)),
                ('sender_phone', models.IntegerField()),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_address', models.CharField(max_length=80)),
                ('receiver_name', models.CharField(max_length=50)),
                ('receiver_phone', models.IntegerField()),
                ('receiver_email', models.EmailField(max_length=254)),
                ('receiver_address', models.CharField(max_length=80)),
                ('parcel_description', models.CharField(max_length=200)),
                ('dispatch_location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('In transit', 'Intransit'), ('Picked Up', 'Picked'), ('Arrived', 'Arrived'), ('Delivered', 'Delivered'), ('On Hold', 'Onhold')], default='In transit', max_length=15)),
                ('dispatch_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_date', models.DateField()),
                ('current_location', models.CharField(max_length=200)),
            ],
        ),
    ]
